@User.Api_HostAddress = http://localhost:5208

###
POST {{User.Api_HostAddress}}/api/users/register/
Content-Type: application/json

{
  "name": "Bob Blue",
  "email": "bob@blue.com",
  "password": "Bobblue1"
}

###
POST {{User.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "email": "bob@blue.com",
    "password": "Bobblue1"
}
